[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
| __pycache__
| .pyc
'''

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
ignore_errors = false
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
check_untyped_defs = true
disallow_untyped_calls = false
disallow_untyped_decorators = true
strict_equality = true
implicit_reexport = false
